### ISSUE TITLE
time/date in UTC.

### ISSUE THREAD

**Issue by nickrout** [qJake/HADotNet.CommandCenter#1]
The time/date tile seems to show the wrong time, for me (UTC -1200 - Pacific/Auckland) it is showing 3.47 am not 3:47 pm.

**Comment by qJake** [comment]
@nickrout I suspect that this may be due to the container having a different default system timezone than where you actually reside. Either way, the date tile should support international formatting regardless (how very *American* of me to hard-code the date/time strings 😉) so I've enhanced the Date tile to support whatever format strings and time zones you'd like to set! You can even have multiple date tiles now with different timezones displaying!

![image](https://user-images.githubusercontent.com/652006/64080280-cb18ea80-ccb7-11e9-8998-de65ab3b8df5.png)

![image](https://user-images.githubusercontent.com/652006/64080282-d0763500-ccb7-11e9-906f-119efb658d2e.png)

This will be released in the next release (likely version 0.4.0)!

**Comment by qJake** [comment]
[Released!](https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.4.0)
