### ISSUE TITLE
Latest HACC version is 0.6.0

### ISSUE THREAD

**Issue by bowhunt24** [qJake/HADotNet.CommandCenter#100]
Using HACS, with auto update turned on, the latest version I can get is 0.6.0, so no pages and missing lots of other functions that are talked about.

**Comment by qJake** [comment]
Yes, this is by design - v1.x is currently in testing, not out just yet. Those who load HACC manually from Docker receive the beta/faster releases. Those who use the Supervisor add-on interface within HA are still on 0.6/0.7 until 1.0 is fully tested and released.

v1.x will be fully released soon - stay tuned. :)
