### ISSUE TITLE
arm32v7 docker image

### ISSUE THREAD

**Issue by grewhit25** [qJake/HADotNet.CommandCenter#25]
Thanks for all your efforts in creating this project.

Is there a plan for an official (armhf/arm32/arm32v7) docker image that would run the trusted Raspberry Pis with 32 bits OS? I note the current images are all 64 bits releases.

In the meantime I have successfully built a 32bits Raspberry PI image from your original Dockerfile with the following two amendments:

```yml
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.6-bionic-arm32v7 as base
FROM mcr.microsoft.com/dotnet/core/sdk:2.2.401-bionic-arm32v7 as build
```
Thanks again.

**Comment by qJake** [comment]
@grewhit25 I'm actually in the process of upgrading the whole project to .NET Core 3.0 since that version supports a few more platforms (notably, Alpine AMD64 and Alpine ARMv8).

I will see if I can get this to work - either with the images you mentioned or with their 3.0 equivalents.

Hopefully in the end we'll have a `linux-ubuntu-arm32v7` tag in this folder:

https://github.com/qJake/HADotNet.CommandCenter/tree/master/Docker

**Comment by grewhit25** [comment]
@qJake Excellent and thanks for your commitment. Good luck with the upgrade.

**Comment by qJake** [comment]
This will be fixed in 0.5.0, releasing this weekend sometime!

**Comment by qJake** [comment]
@grewhit25 Try out our new Hass.io Addon, or if you aren't on Hass.io, check out the documentation here:

https://github.com/qJake/HADotNet.CommandCenter/wiki/Installing-via-Docker

In particular, you'll want to try:

```cmd
docker pull qjake/hacc:latest-linux-debian-arm32v7
docker run -p 8095:8095 qjake/hacc:latest-linux-debian-arm32v7
```

Considering this as fixed since we have an ARM32v7 image - if you experience any issues with this image, please feel free to open a new request! 😃

**Comment by grewhit25** [comment]
@qJake A really good job. I am not on Hass.io but running you latest arm32v7 tag.

Just an aside, you may be able to do away with you tags if you were to adopt Docker's multiarch with manifest approach.

Eitherway, thanks again and looking forward to your future enhancements.
