### ISSUE TITLE
Lost configuration after upgrading to latest image

### ISSUE THREAD

**Issue by max-rh** [qJake/HADotNet.CommandCenter#26]
Hi Jake,

Thanks a lot for an amazing project; Finally a well designed easy to use dashboard for HA.

I just have an issue; I have HACC, HA and pretty much everything running in docker containers, and I have "watchtower" automatically upgrading them, so unless my containers are bound to volumes they will lose the configuration when updated.

Can HACC save its configuration to a volume ?

Thanks

**Comment by qJake** [comment]
@max-rh Someone in this thread got persistent configuration saving working with Docker, I think around this post:

https://community.home-assistant.io/t/hacc-home-assistant-command-center/134843/60

You'll need to make sure both files/directories exist, and if you map those volume paths, it should persist.

Additionally, in 0.5.0, I added an import/export of the config so that you can back up your configuration if you'd like, either periodically or before watchtower updates the container!

**Comment by max-rh** [comment]
Thanks Jake; it worked :)
