### ISSUE TITLE
Set default layout and tile size

### ISSUE THREAD

**Issue by nickrout** [qJake/HADotNet.CommandCenter#3]
By default these are all set at zero. I wondered for some time why I wasn't seeing a page, or anything in the layout preview. Perhaps set to sensible defaults- say 640x480 with 120 sized tiles.

**Comment by qJake** [comment]
I've set some sensible defaults for these settings so that a layout preview now appears by default. I did some math so that you get an 8x9 grid with 100px tiles and 6px spacing by default which should fit most displays and look good out of the box - and users should be customizing these numbers hopefully anyway. 😏

**Comment by qJake** [comment]
[Released!](https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.4.0)
