### ISSUE TITLE
Add support for Google Calendar 

### ISSUE THREAD

**Issue by wzwick** [qJake/HADotNet.CommandCenter#32]
I think a fair number of users would like to see our upcoming schedule on the dashboard (something like atomic calendar)
could this be considered for future release?

**Comment by qJake** [comment]
I was almost going to say that this isn't possible because HA only stores the most recent event, but I dug and found an undocumented API at `/api/calendars/<cal.entity>?start=X&end=X` that lets you pull multiple events.

So I think this is pretty doable, and would be a good addition! Definitely something I'd use myself. 🙂
