### ISSUE TITLE
Support HassIO Ingress

### ISSUE THREAD

**Issue by johntdyer** [qJake/HADotNet.CommandCenter#43]
## Describe the new functionality
Hass.io add-ons can make use of [ingress](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/) to enable seemly integration w/ the UI
## What will it look like on the dashboard?
It would show up on Hass not HACC

## How will it work for standalone users vs. Hass.io Addon users?
I would think it would be only available for Hass.io user, so standalone users would presumably not be impacted

**Comment by qJake** [comment]
This is planned for the next release! Definitely going to have this functionality.

**Comment by qJake** [comment]
After actually attempting to implement this, I have unfortunately found out that it is not possible to support Ingress at this time, due to how Home Assistant embeds/rewrites the HTML to fit inside of the HA/Lovelace interface.

Closing for now, but will reopen if I find a way to support it in the future or something changes.
